server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: http://github.com/dqqzj/finchley.git
          username: username
          password: password
          search-paths: config-repo
        default-label: master
    bus:
      trace:
        enabled: true
  rabbitmq:
    addresses: 192.168.20.10:5672,192.168.20.4:5672,192.168.20.19:5672
    username: username
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://username:password@192.168.20.20:8761/eureka/,http://username:password@192.168.20.24:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: "*"
        allowed-origins: "*"