server:
  port: 8762
  servlet:
    session:
      cookie:
        name: ZUUL
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://10.173.48.104:9411
  sleuth:
    messaging:
      rabbit:
        enabled: true
    sampler:
      probability: 0.6
eureka:
  client:
    service-url:
      defaultZone: http://deloitte:deloitte@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:9060/oauth/token
      user-authorization-uri: http://localhost:9060/oauth/authorize
      client-id: client
      client-secret: secret
    resource:
      user-info-uri: http://localhost:9060/user/me
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000