server:
  port: 9060
  servlet:
    session:
      cookie:
        name: OAUTH
spring:
  application:
    name: oauth
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://10.173.48.66:3306/zqin?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: ocr
    password: Deloitte!@
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://deloitte:deloitte@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always